# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

include: ["_pages"]

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: vsamy
email: vincent.samy@lirmm.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  vsamy

# For handling post excerpt
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
gems:
  - github-pages
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

menu-lang:
  en:
    home:
      name: Home
      url: "home/"
    about:
      name: About
      url: "about/"
    blog:
      name: Papers
      url: "papers/"
    repo:
      name: Git repository
      url: "git-repository/"
  fr:
    home:
      name: Accueil
      url: "accueil/"
    about:
      name: À propos
      url: "a-propos/"
    blog:
      name: Articles
      url: "articles/"
    repo:
      name: Dépôt git
      url: "dépôt-git/"
  jp:
    home:
      name: ホーム
      url: "ホーム/"
    about:
      name: 私について
      url: "私について/"
    blog:
      name: 記事
      url: "記事/"
    repo:
      name: ギット・リポジトリ
      url: "ギット・リポジトリ/"